# -*- coding: utf-8 -*-
"""Yolo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLOym-NJnTJ29EFq9WopizlrxgeFUPp7
"""

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

# set up environment
os.environ["DATASET_DIRECTORY"] = "/content/datasets"

from google.colab import drive
drive.mount('/content/drive')

best_model_path = "/content/drive/My Drive/Árvores/best.pt"
test_images_path = "/content/drive/My Drive/Árvores/Imagens_Teste"
output_path = "/content/drive/My Drive/Árvores/Resultados"

!python detect.py --weights "{best_model_path}" --source "{test_images_path}" --project "{output_path}" --name results --exist-ok

from roboflow import Roboflow
rf = Roboflow(api_key="30fnPU6bg1n0VE0Iw6oj")
project = rf.workspace("auladetopicos").project("chess-uhtx3")
#dataset = project.version(1).download("yolov5")
dataset = "/content/drive/My Drive/Árvores/Imagens_Teste"

!python train.py --img 640 --batch 16 --epochs 1500 --data {dataset.location}/data.yaml --weights yolov5l.pt --cache

# Commented out IPython magic to ensure Python compatibility.
# Start tensorboard
# Launch after you have started training
# logs save in the folder "runs"
# %load_ext tensorboard
# %tensorboard --logdir runs

!python detect.py --hide-label --hide-conf --weights runs/train/exp/weights/best.pt --img 640 --conf 0.1 --source {dataset.location}/test/images

import glob
import matplotlib.pyplot as plt
import cv2
from google.colab.patches import cv2_imshow


for imageName in glob.glob('/content/yolov5/runs/detect/exp/*.jpg'):
    image = cv2.imread(imageName)
    cv2_imshow(image)
    print("\n")

!pip install ultralytics
!pip install git+https://github.com/ultralytics/yolov5

from ultralytics import YOLO
from yolov5 import YOLO
import os

from google.colab import drive
drive.mount('/content/drive')

model = YOLO('/content/drive/My Drive/Árvores/Yolo_Treinado/best.pt')

test_images_folder = '/content/drive/My Drive/Árvores/Yolo_Imagens_Teste'

results = model.predict(source=test_images_folder, save=True, save_txt=True)

# 'save=True' salva as imagens com as previsões (caixas delimitadoras) no diretório 'runs/detect/predict'
# 'save_txt=True' salva os resultados das previsões em arquivos .txt no mesmo diretório

